In [ ]:
#Create a sample DataFrame
import pandas as pd
df = pd.DataFrame({'numbers': [1, 2, 3], 'colors': ['red', 'white', 'blue']})
print(df)
print()
df1 = pd.DataFrame({'numbers': [1, 2, 3], 'colors': ['red', 'white', 'blue']}, columns = ['numbers', 'colors'])
print(df1)

   numbers colors
0        1    red
1        2  white
2        3   blue

   numbers colors
0        1    red
1        2  white
2        3   blue


In [ ]:
#Create a sample DataFrame using Numpy
import numpy as np
import pandas as pd

df = pd.DataFrame(np.random.randn(5, 3), columns = ['N1', 'N2', 'N3'])
print(df)

         N1        N2        N3
0  0.467062  0.056683 -1.647267
1 -0.239702  0.069407  0.782263
2  1.212476  1.723058 -0.907520
3  0.203596  1.882131 -0.686052
4  0.849410  0.425569 -1.203220


In [ ]:
#Create a DataFrame from a dictionary of lists
import pandas as pd
df = pd.DataFrame ({'N1' : [1, 2, 3, 4], 'N2' : [4, 3, 2, 1]})
print(df)

   N1  N2
0   1   4
1   2   3
2   3   2
3   4   1


In [ ]:
#Create a DataFrame from a list of dictionaries
import pandas as pd
L = [{'Name' : 'John', 'Last Name' : 'Smith'}, {'Name' : 'Mary', 'Last Name' : 'Wood'}]
df = pd.DataFrame(L)
print(df)

   Name Last Name
0  John     Smith
1  Mary      Wood


In [ ]:
#Input from text file
from google.colab import files
uploaded = files.upload()
import numpy as np
import pandas as pd

data = np.loadtxt("sample.txt", delimiter = ',')
print(data)
print()
data1 = pd.read_csv("sample.txt", delimiter = ',')
print(data1)

Saving sample.txt to sample (2).txt
[[1.  2.1 0.1]
 [2.  4.5 9. ]
 [3.  5.5 2.1]
 [4.  2.3 3.3]
 [5.  7.7 8.8]]

   1  2.1  0.1
0  2  4.5  9.0
1  3  5.5  2.1
2  4  2.3  3.3
3  5  7.7  8.8


In [ ]:
from google.colab import files
uploaded = files.upload()
import numpy as np
import pandas as pd

data = pd.read_csv('sample1.txt', delimiter = ',')
print(data)
print("Print column Score")
print(data.Score)

Saving sample1.txt to sample1.txt
   ID  Weight  Score
0   1     2.1    0.1
1   2     4.5    9.0
2   3     5.5    2.1
3   4     2.3    3.3
4   5     7.7    8.8
Print column Score
0    0.1
1    9.0
2    2.1
3    3.3
4    8.8
Name: Score, dtype: float64


In [ ]:
#Access data
import numpy as np
import pandas as pd

df = pd.DataFrame(np.random.randn(10, 3), columns = ['N1', 'N2', 'N3'])
print(df)
print()

print(df.head(5))
print()

print(df.tail(5))
print()

N2 = df['N2']
print(N2)
print()

N = df[['N1', 'N2']]
print(N)
print()

print(df[1:-2])

         N1        N2        N3
0 -0.660939 -0.317117 -1.001870
1  0.389310  1.070788 -0.101855
2  0.419701  1.293130 -0.334309
3  0.504768  1.256475 -1.094820
4 -1.114501 -0.319483 -0.095160
5 -1.386744  0.053153 -0.809797
6  1.361766 -0.391588 -0.719108
7 -0.338325 -0.182194  0.845304
8 -1.517021  0.856302  0.053759
9  1.836783 -0.607469 -0.414631

         N1        N2        N3
0 -0.660939 -0.317117 -1.001870
1  0.389310  1.070788 -0.101855
2  0.419701  1.293130 -0.334309
3  0.504768  1.256475 -1.094820
4 -1.114501 -0.319483 -0.095160

         N1        N2        N3
5 -1.386744  0.053153 -0.809797
6  1.361766 -0.391588 -0.719108
7 -0.338325 -0.182194  0.845304
8 -1.517021  0.856302  0.053759
9  1.836783 -0.607469 -0.414631

0   -0.317117
1    1.070788
2    1.293130
3    1.256475
4   -0.319483
5    0.053153
6   -0.391588
7   -0.182194
8    0.856302
9   -0.607469
Name: N2, dtype: float64

         N1        N2
0 -0.660939 -0.317117
1  0.389310  1.070788
2  0.419701  1.293130
3  0.50

In [ ]:
#Exercise 1
from google.colab import files
uploaded = files.upload()
import numpy as np
import pandas as pd

import pandas as pd
import numpy as np

data = pd.read_csv("iris.csv")
df = pd.DataFrame(data)

print(df.head(5))
print()

def count(data):
    count = 0
    for i in range(0, len(data) + 1):
        count += 1
    return count

def mean(data):
    n = count(data)
    sum = data.sum()
    return sum / n

def std(data):
    n = count(data)
    m = mean(data)
    square_diff = [(x - m) ** 2 for x in data]
    mean_square_diff = sum(square_diff) / n
    std = mean_square_diff ** (1 / 2)
    return std

def min(data):
    return data.min()

def max(data):
    return data.max()

s1 = df["sepal_length"]
s2 = df["sepal_width"]
s3 = df["petal_length"]
s4 = df["petal_width"]

dt = pd.DataFrame({
        "sepal_length": [count(s1), mean(s1), std(s1), min(s1), max(s1)],
        "sepal_width": [count(s2), mean(s2), std(s2), min(s2), max(s2)],
        "petal_length": [count(s3), mean(s3), std(s3), min(s3), max(s3)],
        "petal_width": [count(s4), mean(s4), std(s4), min(s4), max(s4)],})

new_row_name = ["count", "mean", "std", "min", "max"]
dt = dt.set_index(pd.Index(new_row_name))
print(dt)

Saving iris.csv to iris (28).csv
   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

       sepal_length  sepal_width  petal_length  petal_width
count    151.000000   151.000000    151.000000   151.000000
mean       5.804636     3.033775      3.733775     1.190728
std        0.823468     0.431185      1.752872     0.758131
min        4.300000     2.000000      1.000000     0.100000
max        7.900000     4.400000      6.900000     2.500000


In [ ]:
from google.colab import files
uploaded = files.upload()
import numpy as np
import pandas as pd

data = pd.read_csv("population.csv")
print(data.head(5))
print()

dt = data.groupby(["Country Name", "Country Code"]).agg({"Year": ["count", "mean", "std", "min", "max"]})
print(dt)

Saving population.csv to population (4).csv
  Country Name Country Code  Year      Value
0   Arab World          ARB  1960   92197753
1   Arab World          ARB  1961   94724510
2   Arab World          ARB  1962   97334442
3   Arab World          ARB  1963  100034179
4   Arab World          ARB  1964  102832760

                                 Year                               
                                count    mean        std   min   max
Country Name       Country Code                                     
Afghanistan        AFG             59  1989.0  17.175564  1960  2018
Albania            ALB             59  1989.0  17.175564  1960  2018
Algeria            DZA             59  1989.0  17.175564  1960  2018
American Samoa     ASM             59  1989.0  17.175564  1960  2018
Andorra            AND             59  1989.0  17.175564  1960  2018
...                               ...     ...        ...   ...   ...
West Bank and Gaza PSE             29  2004.0   8.514693  1990  